# Generated by Django 5.0.4 on 2024-08-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0002_hazardouswaste_nonbiowaste'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardouswaste',
            name='waste_type',
            field=models.CharField(choices=[('e_waste', 'E waste'), ('medical_waste', 'Medical Waste'), ('chemicals', 'Chemicals'), ('pesticides_herbicides', 'Pesticides/Herbicides'), ('heavy_metals', 'Heavy Metals'), ('asbestos', 'Asbestos'), ('industrial_waste', 'Industial Waste'), ('automobile_degreasers', 'Automobile & Degreasers')], default='e_waste', max_length=50),
        ),
        migrations.AddField(
            model_name='hazardouswaste',
            name='waste_weight',
            field=models.CharField(blank=True, choices=[('enter_manually', 'Enter Manually'), ('pickup', 'Check on pickup')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nonbiowaste',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('glass', 'Glass'), ('synthetic_fabrics', 'Synthetic fabrics'), ('rubber', 'Rubber'), ('styrofoam', 'Styrofoam'), ('aluminum_foil', 'Aluminum Foil')], default='plastic', max_length=50),
        ),
        migrations.AddField(
            model_name='nonbiowaste',
            name='waste_weight',
            field=models.CharField(choices=[('enter_manually', 'Enter the weight mnually'), ('pickup', 'Check on pick up')], default='pickup', max_length=50),
        ),
        migrations.AddField(
            model_name='waste',
            name='waste_type',
            field=models.CharField(choices=[('food_waste', 'Food Waste'), ('wooden_items', 'Wooden Items'), ('paper_waste', 'Paper Waste'), ('cotton_wool', 'Cotton/Wool Materials'), ('garden_waste', 'Garden Waste'), ('animal_waste', 'Animal Waste'), ('tea_bags_coffee_filters', 'Tea Bags & Coffee Filters'), ('bamboo_products', 'Bamboo Products')], default='food_waste', max_length=50),
        ),
        migrations.AddField(
            model_name='waste',
            name='waste_weight',
            field=models.CharField(blank=True, choices=[('enter_manually', 'Enter the weight manually'), ('pickup', 'Check on pick up')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hazardouswaste',
            name='weight_option',
            field=models.CharField(choices=[('manual', 'Enter manually'), ('pickup', 'Check later on pick up')], max_length=50),
        ),
        migrations.AlterField(
            model_name='nonbiowaste',
            name='weight_option',
            field=models.CharField(choices=[('manual', 'Enter manually'), ('pickup', 'Check later on pick up')], max_length=50),
        ),
        migrations.AlterField(
            model_name='waste',
            name='weight_option',
            field=models.CharField(choices=[('manual', 'Enter manually'), ('pickup', 'Check later on pick up')], max_length=50),
        ),
    ]
