# Generated by Django 5.0.4 on 2024-08-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0003_hazardouswaste_waste_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HazardousWaste',
        ),
        migrations.DeleteModel(
            name='NonBioWaste',
        ),
        migrations.DeleteModel(
            name='Waste',
        ),
    ]
