# Generated by Django 5.0.4 on 2024-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0004_delete_hazardouswaste_delete_nonbiowaste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biowaste',
            fields=[
                ('waste_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('waste_weight', models.CharField(max_length=50)),
                ('manual_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waste_type', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
    ]
