# Generated by Django 5.0.4 on 2024-09-05 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0006_hazardouswaste_nonbiowaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('pickup_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('waste_type', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('payment_status', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
