# Generated by Django 5.0.4 on 2024-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0007_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='pickup_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
