# Generated by Django 5.0.4 on 2024-09-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0009_handlers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(choices=[('Engaged', 'Engaged'), ('Free to pick', 'Free to pick')], default='Free to pick', max_length=20)),
            ],
        ),
    ]
