# Generated by Django 5.0.4 on 2024-09-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0011_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
