# Generated by Django 5.0.4 on 2024-09-24 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0012_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WM_app.pickup')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WM_app.staff')),
            ],
        ),
    ]
