# Generated by Django 5.0.4 on 2024-09-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0013_completedpickup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedPickup',
        ),
    ]
