# Generated by Django 5.0.4 on 2024-09-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0014_delete_completedpickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedPickup',
            fields=[
                ('Completed_Pickid', models.AutoField(primary_key=True, serialize=False)),
                ('Staff_name', models.CharField(max_length=255)),
                ('Staff_ID', models.IntegerField()),
            ],
        ),
    ]
