# Generated by Django 5.0.4 on 2024-09-26 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0015_completedpickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=255)),
                ('pickup_id', models.IntegerField()),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
