# Generated by Django 5.0.4 on 2024-10-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0016_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedpickup',
            name='Pickup_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
