# Generated by Django 5.0.4 on 2024-10-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_app', '0017_completedpickup_pickup_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=75)),
                ('cust_mail', models.EmailField(max_length=254)),
                ('cust_message', models.CharField(max_length=1000)),
            ],
        ),
    ]
